BEGIN;

DROP TABLE IF EXISTS "member", "draw", "participant", "whishlist";

CREATE TABLE IF NOT EXISTS "member" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "firstname" TEXT,
    "lastname" TEXT,
    "email" TEXT NOT NULL,
    "password" TEXT NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS "draw" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "budget" INTEGER,
    "member_id" INTEGER NOT NULL REFERENCES "member"("id")
);

CREATE TABLE IF NOT EXISTS "participant" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "firstname" TEXT NOT NULL,
    "lastname" TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS "wishlist" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "item_list" TEXT,
    "participant_id" INTEGER NOT NULL REFERENCES "participant"("id")
);

CREATE TABLE IF NOT EXISTS "draw_has_participant" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "draw_id" INTEGER NOT NULL REFERENCES "draw"("id"),
    "participant_id" INTEGER NOT NULL REFERENCES "participant"("id")
);

COMMIT;